name: Auto-merge Dependabot updates

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Auto-merge patch & minor only
        uses: fastify/github-action-merge-dependabot@v3
        with:
          target: minor         # merges patch + minor; NEVER majors
          merge-method: squash  # or rebase
