name: Publish to PyPI on GitHub Release
on:
  release:
    types: [published]
  workflow_run:
    workflows: ["Release Please"]
    types: [completed]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Ensure build tooling
        run: python -m pip install --upgrade pip build twine

      - name: Build sdist and wheel
        run: python -m build

      - name: Validate metadata (twine check)
        run: twine check dist/*

      - name: Publish to PyPI (Trusted Publishing)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          print-hash: true
          skip-existing: true     # safe re-runs
          attestations: true      # publish PEP 740 attestations to PyPI